import { StyleSheet } from "react-native";

import { COLORS, SIZES, FONTS } from "../../constants";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  wrapper: {
    flex: 1,
    backgroundColor: COLORS.themeg,
    flexDirection: "column",
  },
  instructions: {
    marginTop: SIZES.medium,
  },
  upperRow: {
    width: SIZES.width - 20,
    marginHorizontal: SIZES.xSmall,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    position: "absolute",
    backgroundColor: COLORS.themew,
    borderRadius: SIZES.large,
    top: SIZES.xxSmall,
    zIndex: 999,
    minHeight: 120,
  },
  topheading: {
    fontFamily: "bold",
    fontSize: SIZES.large,
  },
  lowerRow: {
    marginTop: 140,
    backgroundColor: COLORS.themew,
    // minHeight: SIZES.height,
    width: SIZES.width - 20,
    marginStart: 10,
    borderRadius: SIZES.medium,
    paddingHorizontal: 3,
  },
  upperButtons: {
    width: SIZES.width - 20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: SIZES.xSmall,
    top: SIZES.xxSmall,
    height: SIZES.xxLarge * 1.4,
  },
  backBtn: {
    left: 10,
    position: "absolute",
    top: 3,
  },
  buttonWrap: {
    backgroundColor: COLORS.themeg,
    padding: 15,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    marginEnd: 10,
  },
  header: {
    fontSize: 24,
    marginBottom: 20,
  },
  amount: {
    fontSize: 20,
    marginBottom: 20,
    fontFamily: "semibold",
    textAlign: "center",
  },
  stepContainer: {
    width: "100%",
    marginBottom: 20,
  },
  stepContainerInner: { justifyContent: "center", alignItems: "center", padding: 20 },
  input: {
    height: 40,
    borderColor: "gray",
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  nextText: {
    fontFamily: "semibold",
    textAlign: "center",
    color: COLORS.white,
    fontSize: SIZES.medium,
  },
  button1: {
    height: 50,
    borderRadius: SIZES.medium,
    backgroundColor: COLORS.themey,
    justifyContent: "center",
    alignItems: "center",
  },

  imageContainer: {
    height: 100,
    width: 100,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: SIZES.medium,
    borderColor: COLORS.themeg,
    borderWidth: 1,
  },
  image: {
    borderRadius: SIZES.medium,
    height: "100%",
    width: "100%",
  },
  rowitem: {
    flexDirection: "row",
    overflow: "hidden",
    justifyContent: "space-between",
    width: SIZES.width / 2 + 30,
  },
  title: {
    fontFamily: "semibold",
    fontSize: SIZES.medium,
  },
  semititle: {
    fontFamily: "regular",
    fontSize: SIZES.medium - 3,
  },
  size: {
    fontFamily: "regular",
    fontSize: SIZES.medium - 2,
    paddingStart: 2,
  },
  details: {
    gap: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    width: SIZES.width / 2,
  },
  containerx: {
    flexDirection: "row",
    marginBottom: SIZES.small,
    backgroundColor: COLORS.themeg,
    padding: 10,
    gap: 10,
    borderRadius: SIZES.medium,
  },
  uppDetail: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  containLottie: {
    justifyContent: "center",
    alignItems: "center",
    width: SIZES.width - 20,
    minHeight: SIZES.height - 150,
  },
  errorMessage: {
    fontFamily: "semibold",
    fontSize: SIZES.large,
    marginBottom: 30,
  },
  dot: (backgroundColor) => ({
    width: 50,
    height: 7,
    backgroundColor,
    borderRadius: 15,
  }),
  paginationContainer: {
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    height: 30,
  },
  stepsheader: {
    paddingVertical: 10,
    textAlign: "left",
    justifyContent: "flex-start",
  },
  stepstext: {
    fontFamily: "regular",
    color: COLORS.gray2,
  },
  previous: {
    height: 60,
    width: 60,
    backgroundColor: COLORS.themey,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  next2wrapper: {
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    marginTop: 20,
    // position: "absolute",
    // bottom: 20,
  },
  next2: {
    justifyContent: "center",
    alignItems: "center",
    width: SIZES.width - 100,
    backgroundColor: COLORS.themey,
    borderRadius: SIZES.xxLarge,
    height: 60,
  },
  input: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.themeg,
    padding: 10,
    borderRadius: SIZES.medium,
    marginBottom: 10,
    width: SIZES.width - 40,
    marginStart: 5,
  },
  input2: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.themeg,
    borderRadius: SIZES.xLarge,
    width: SIZES.width - 40,
    marginStart: 5,
  },
  input22: {
    backgroundColor: COLORS.themeg,
    borderRadius: SIZES.medium,
  },
  label: {
    fontSize: SIZES.medium,
    fontWeight: "bold",
    marginBottom: SIZES.xSmall,
    color: COLORS.themey,
    marginStart: SIZES.small,
  },
  shippingContainer: {
    minHeight: SIZES.height / 2,
    marginTop: SIZES.xxLarge,
  },
  buttonText: {
    color: COLORS.lightWhite,
    fontFamily: "lufgaBold",
    fontSize: SIZES.medium,
  },
  error: { color: "red", marginBottom: 10, marginStart: 10, marginTop: 20 },
  errorb: {
    borderWidth: 0.54,
    borderColor: COLORS.red,
  },
  successb: {
    borderWidth: 0.54,
    borderColor: COLORS.green,
  },
  animationWrapper: {
    width: 200,
    height: 200,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  animation: {
    width: "100%",
    height: "100%",
  },
  buttonHome: {
    position: "absolute",
    bottom: 20,
    left: 10,
    right: 10,
    backgroundColor: COLORS.themey,
    height: SIZES.xxLarge + 20,
    borderRadius: SIZES.medium,
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "white",
    margin: 20,
    borderRadius: 10,
    padding: 20,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    paddingHorizontal: 10,
    height: 40,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
  },
  searchIcon: {
    fontSize: 20,
    marginLeft: 10,
  },
  countryItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  flag: {
    fontSize: 24,
    marginRight: 10,
  },
  flagWidth: {},
  countryName: {
    flex: 1,
    fontSize: 16,
    color: "#333",
  },
  countryCode: {
    fontSize: 16,
    color: "#888",
  },

  closeButton: {
    marginTop: 20,
    backgroundColor: "#007BFF",
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 5,
  },
  closeButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  deliveryMethod: {
    minHeight: 300,
  },

  deliveryHead: {
    fontSize: 18,
    fontWeight: "bold",

    padding: 15,
  },
  deliveryOptions: {
    borderRadius: 10,
    padding: 10,
  },
  optionCard: {
    backgroundColor: COLORS.themew,
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  selectedCard: {
    backgroundColor: COLORS.themeg,
    borderColor: "#00a478",
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: "bold",
  },
  optionPrice: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
  },
  optionDescription: {
    fontSize: 14,

    marginTop: 5,
  },
  selectedText: {
    color: COLORS.themeb,
  },
  selectedText2: {
    color: COLORS.themeb,
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 7,
  },
  pickupContainer: {
    marginTop: 10,
  },
  //   label: {
  //     fontSize: 16,
  //     fontWeight: "bold",
  //     marginBottom: 10,
  //     marginStart: 10,
  //   },
  storeList: {
    gap: 10,
  },
  storeCard: {
    backgroundColor: "#f9f9f9",
    padding: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  selectedStore: {
    color: COLORS.themew,
    backgroundColor: "#34D399", // Green highlight
    borderColor: "#059669",
  },
  storeTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  storeDetails: {
    fontSize: 14,
  },
  selectedStored: {
    color: COLORS.themew,
  },
  flexme: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  descriptionInput: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.themeg,
    padding: 10,
    borderRadius: SIZES.medium,
    marginBottom: 10,
    width: SIZES.width - 40,
    marginStart: 5,
    textAlignVertical: "top",
    height: 100,
  },
});
