import { StyleSheet } from "react-native";

import { COLORS, SIZES, FONTS } from "../../../constants";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorText: {
    color: COLORS.text,
    fontSize: 16,
    textAlign: "center",
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryText: {
    color: COLORS.background,
    fontWeight: "600",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  headerTitle: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: "600",
  },
  scrollContainer: {
    marginTop: 90,

    background: COLORS.red,
    flex: 1,
    paddingHorizontal: 10,
  },
  profileCard: {
    backgroundColor: "#585B4A",
    borderRadius: 16,
    padding: 10,
    overflow: "hidden",
    height: 220,
    marginBottom: 20,
    alignItems: "center",
  },
  doctorImage: {
    ...StyleSheet.absoluteFill,
    resizeMode: "contain",
  },
  doctorInfo: {
    // alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 15,
  },
  doctorName: {
    color: COLORS.themew,
    fontSize: 20,
    fontFamily: "bold",
    marginBottom: 5,
  },
  doctorSpecialty: {
    color: COLORS.themew,
    fontSize: 14,
    fontFamily: "lufgaBold",
  },
  wholeCardView: {
    backgroundColor: COLORS.themeg,
    padding: 5,
    borderRadius: SIZES.medium,
  },
  actionButtons: {
    position: "absolute",
    bottom: 10,
    left: 10,
    right: 10,
    borderRadius: SIZES.large,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: SIZES.width - 50,
    padding: 5,
    paddingHorizontal: SIZES.small,
  },
  flexEnd: {
    flexDirection: "row",
    gap: 10,
    justifyContent: "flex-end",
  },
  actionButton: {
    backgroundColor: COLORS.primary,
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: COLORS.cardBackground,
    borderRadius: 12,
    marginBottom: 10,
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  statNumber: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "700",
  },
  statLabel: {
    color: COLORS.textSecondary,
    fontSize: 12,
  },
  availabilitySection: {
    marginVertical: 20,
  },
  availabilityHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  sectionTitle: {
    color: COLORS.themey,
    fontSize: SIZES.large,
    fontWeight: "600",
  },
  monthSelector: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  monthText: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "500",
  },
  calendar: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  calendarDay: {
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 8,
    minWidth: 40,
  },
  selectedDay: {
    backgroundColor: COLORS.primary,
  },
  dayNumber: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  dayName: {
    color: COLORS.textSecondary,
    fontSize: 12,
  },
  selectedDayText: {
    color: COLORS.themew,
  },
  aboutSection: {
    marginBottom: 100,
    paddingHorizontal: 10,
  },
  aboutText: {
    color: COLORS.textSecondary,
    fontSize: SIZES.medium,
    fontFamily: "medium",
    lineHeight: 20,
    marginTop: 10,
  },
  bookingContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.background,
    paddingHorizontal: 10,
    paddingVertical: 20,
    paddingBottom: 10,
  },
  bookButton: {
    backgroundColor: COLORS.primary,
    borderRadius: SIZES.xxLarge,
    paddingVertical: 16,
    alignItems: "center",
  },
  bookButtonText: {
    color: COLORS.themew,
    fontSize: 16,
    fontWeight: "700",
  },
  blurView: {
    ...StyleSheet.absoluteFillObject,
  },
  upperRow: {
    width: SIZES.width - 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    position: "absolute",
    backgroundColor: COLORS.themew,
    borderRadius: SIZES.large,
    top: SIZES.small,
    marginStart: 10,
    minHeight: 70,
    zIndex: 999,
  },

  heading: {
    color: COLORS.themeb,
    marginLeft: 5,
    fontFamily: "italic",
    fontSize: SIZES.large,
  },
  buttonWrap: {
    backgroundColor: COLORS.themeg,
    padding: 15,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    marginEnd: 10,
    marginStart: 10,
  },
  lovebuy: {
    flexDirection: "row",
  },
  buttonWrap1: {
    backgroundColor: COLORS.themeg,
    padding: 15,
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 4,
  },
  wrapper: {
    flex: 1,
    backgroundColor: COLORS.themew,
    alignItems: "center",
    justifyContent: "center",
  },
  statsb: {
    borderRadius: 100,
    backgroundColor: COLORS.white,
    padding: SIZES.small,
  },
  numberHolder: {
    flexDirection: "column",
    gap: 5,
  },
  timeslots: {
    borderRadius: SIZES.large,
    padding: 10,
    backgroundColor: COLORS.themeg,
  },
  slotsHolder: {
    marginVertical: 20,
    display: "flex",
    flexDirection: "row",
    gap: 10,
  },
  timeslot: {
    fontFamily: "lufgaSemiBold",
  },
  backgroundLoader: {
    position: "absolute",
    top: 70,
    right: SIZES.width / 2,
    zIndex: 10,
  },
  input: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.themeg,
    padding: 10,
    borderRadius: SIZES.xxLarge,
    marginBottom: 10,
    width: SIZES.width - 30,
    marginStart: 10,
  },
  descriptionInput: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.themeg,
    padding: 10,
    borderRadius: SIZES.medium,
    marginBottom: 10,
    width: SIZES.width - 30,
    marginStart: 10,
    textAlignVertical: "top",
    height: 100,
  },
  nonEditable: {
    backgroundColor: "lightgray",
  },
  availabilityRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    paddingLeft: 10,
  },
  submitBtn: {
    backgroundColor: COLORS.primary,
    padding: 15,
    marginTop: 10,
    paddingVertical: 20,
    borderRadius: SIZES.xxLarge,
    alignItems: "center",
  },
  submitText: {
    color: COLORS.white,
    fontWeight: "bold",
  },
  pickerWrapper: {
    marginBottom: 10,
    marginstart: 10,
    paddingLeft: 10,
  },
  pickerLabel: {
    marginBottom: 5,
    fontFamily: "bold",
    fontSize: SIZES.medium,
    color: COLORS.themey,
  },
  picker: {
    height: 40,
    borderColor: "gray",
    borderWidth: 1,
    color: COLORS.black,
    backgroundColor: COLORS.themeg,
    borderRadius: SIZES.medium,
  },
  heading: {
    fontFamily: "bold",
    textTransform: "uppercase",
    fontSize: SIZES.medium,
    textAlign: "center",
    color: COLORS.themeb,
  },

  label: {
    fontFamily: "bold",
    fontSize: SIZES.medium,
    color: COLORS.themey,
    marginBottom: 5,

    paddingLeft: 10,
    textAlign: "left",
  },
  rowNames: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  inputH: {
    flex: 1,
    backgroundColor: COLORS.themeg,
    padding: 10,
    borderRadius: SIZES.large,
    marginBottom: 10,
    width: SIZES.width - 30,
    marginStart: 10,
  },
  timeslotsH: {
    padding: 10,
    marginTop: 5,
    marginRight: 10,
    backgroundColor: "#f0f0f0",
    borderRadius: SIZES.large,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  timeslotH: {
    fontSize: 16,
    color: "#333",
  },
  slotsHolderH: {
    marginVertical: 5,
    paddingHorizontal: 10,
  },
  instructions: {
    marginBottom: 80,
  },
  dateBox: {
    height: 50,
    display: "flex",
    justifyContent: "space-between",
  },
});
